-- شغّل هذا الملف داخل Supabase Studio > SQL Editor

create table if not exists public.tasks (
  id           bigint generated by default as identity primary key,
  title        text not null,
  quadrant     text not null default 'important-urgent'
               check (quadrant in (
                 'important-urgent',
                 'important-not-urgent',
                 'not-important-urgent',
                 'not-important-not-urgent'
               )),
  completed    boolean not null default false,
  notes        text default '',
  due_date     date,
  duration     integer not null default 1,
  sort_order   integer not null default 0,
  recurrence   text default null
               check (recurrence is null or recurrence in ('daily', 'weekly')),
  recurrence_days integer[] default null,
  created_at   timestamptz not null default now(),
  completed_at timestamptz
);

-- ترحيل للجداول الموجودة مسبقاً
alter table public.tasks add column if not exists sort_order integer not null default 0;
alter table public.tasks add column if not exists recurrence text default null;
alter table public.tasks add column if not exists recurrence_days integer[] default null;

create index if not exists tasks_created_at_idx on public.tasks (created_at desc);
create index if not exists tasks_quadrant_sort_idx on public.tasks (quadrant, sort_order);

alter table public.tasks enable row level security;

drop policy if exists "Allow all access to tasks" on public.tasks;
create policy "Allow all access to tasks"
  on public.tasks
  for all
  using (true)
  with check (true);

-- قد يفشل إن كان الجدول مضافاً مسبقاً للـ publication — هذا طبيعي
do $$
begin
  alter publication supabase_realtime add table public.tasks;
exception when duplicate_object then null;
end $$;
