-- شغّل هذا الملف كامل داخل Supabase Studio > SQL Editor
-- ينشئ جدول المهام مع سياسات أمان أساسية (RLS) ويفعّل التحديث اللحظي (Realtime)

create table if not exists public.tasks (
  id           bigint generated by default as identity primary key,
  title        text not null,
  quadrant     text not null default 'important-urgent'
               check (quadrant in (
                 'important-urgent',
                 'important-not-urgent',
                 'not-important-urgent',
                 'not-important-not-urgent'
               )),
  completed    boolean not null default false,
  notes        text default '',
  due_date     date,
  duration     integer not null default 1,
  created_at   timestamptz not null default now(),
  completed_at timestamptz
);

-- فهرس لتسريع الفرز حسب تاريخ الإنشاء
create index if not exists tasks_created_at_idx on public.tasks (created_at desc);

-- تفعيل الحماية على مستوى الصفوف
alter table public.tasks enable row level security;

-- سياسة مبدئية: تسمح بكل العمليات لأي مستخدم يستخدم مفتاح anon
-- (مناسبة لتطبيق شخصي/فريق صغير بدون تسجيل دخول)
-- إذا رغبت لاحقاً بإضافة مصادقة Supabase Auth، استبدل هذه السياسة بسياسات
-- تعتمد على auth.uid() وأضف عمود user_id.
drop policy if exists "Allow all access to tasks" on public.tasks;
create policy "Allow all access to tasks"
  on public.tasks
  for all
  using (true)
  with check (true);

-- تفعيل البث اللحظي (Realtime) على الجدول
alter publication supabase_realtime add table public.tasks;
